//Test User API

### Register User
POST http://localhost:3000/api/users
Content-Type: application/json
Accept: application/json

{
    "username" : "Dhahika",
    "password" : "123456",
    "name" : "Dhahika Rahmadani"
}

### Login
POST http://localhost:3000/api/users/login
Content-Type: application/json
Accept: application/json

{
    "username" : "Dhahika",
    "password" : "123456"
}

### Get Users
GET http://localhost:3000/api/users/current
Content-Type: application/json
Accept: application/json
Authorization: e1b44839-8abb-4df4-80b1-7f543e362820

### Update User
PATCH http://localhost:3000/api/users/current
Content-Type: application/json
Accept: application/json
Authorization: e1b44839-8abb-4df4-80b1-7f543e362820

{
    "name": "Dhahika R"
}

### Logout
DELETE http://localhost:3000/api/users/logout
Content-Type: application/json
Accept: application/json
Authorization: e1b44839-8abb-4df4-80b1-7f543e362820


// Test Contact API
### Create New Contact
POST http://localhost:3000/api/contacts
Content-Type: application/json
Accept: application/json
Authorization: e1b44839-8abb-4df4-80b1-7f543e362820

{
    "first_name": "Alexander",
    "last_name": "Graham",
    "email": "graham@gamil.com",
    "phone": "085748248241"
}

### List Contact
GET  http://localhost:3000/api/contacts
Content-Type: application/json
Accept: application/json
Authorization: e1b44839-8abb-4df4-80b1-7f543e362820

### Get Contact
GET  http://localhost:3000/api/contacts/4065
Content-Type: application/json
Accept: application/json
Authorization: e1b44839-8abb-4df4-80b1-7f543e362820

### Update Contact
PATCH   http://localhost:3000/api/contacts/4065
Content-Type: application/json
Accept: application/json
Authorization: e1b44839-8abb-4df4-80b1-7f543e362820

{
    "first_name": "Antonio",
    "last_name": "Guller",
    "email": "antonioguller@gamil.com",
    "phone": "085748987645"
}

### Remove Contact
DELETE   http://localhost:3000/api/contacts/4067
Content-Type: application/json
Accept: application/json
Authorization: e1b44839-8abb-4df4-80b1-7f543e362820

// Test Address API

### Add Address
POST http://localhost:3000/api/contacts/4066/addresses
Content-Type: application/json
Accept: application/json
Authorization: e1b44839-8abb-4df4-80b1-7f543e362820

{
    "street": "Jalan Jayabaya",
    "city": "Surabaya",
    "province": "Jawa Timur",
    "country": "Indonesia",
    "postal_code": "242424"
}

### List Address
GET  http://localhost:3000/api/contacts/4066/addresses
Content-Type: application/json
Accept: application/json
Authorization: e1b44839-8abb-4df4-80b1-7f543e362820

### GET Address
GET  http://localhost:3000/api/contacts/4066/addresses/207
Content-Type: application/json
Accept: application/json
Authorization: e1b44839-8abb-4df4-80b1-7f543e362820

### Update Address
PATCH   http://localhost:3000/api/contacts/4066/addresses/207
Content-Type: application/json
Accept: application/json
Authorization: e1b44839-8abb-4df4-80b1-7f543e362820

{
    "street": "Jalan Hos Cokroaminoto",
    "city": "Ponorogo",
    "province": "Jawa Timur",
    "country": "Indonesia",
    "postal_code": "242424"
}

### Remove Address
DELETE   http://localhost:3000/api/contacts/4066/addresses/208
Content-Type: application/json
Accept: application/json
Authorization: e1b44839-8abb-4df4-80b1-7f543e362820